// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type gui struct {
	win fyne.Window

	gnomeSelect   *widget.Select
	gnomes        *canvas.Image
	iconImage     *canvas.Image
	mainLabel     *widget.Label
	muteButton    *widget.Button
	pauseButton   *widget.Button
	pb            *widget.ProgressBar
	restartButton *widget.Button
	startButton   *widget.Button
	statLabel     *widget.Label
	stopButton    *widget.Button
	labelBox      *fyne.Container
	wideBox       *fyne.Container
}

func newGUI() *gui {
	return &gui{}
}

func (g *gui) makeUI() fyne.CanvasObject {
	g.gnomeSelect = widget.NewSelect([]string{""}, func(s string) {})
	g.gnomes = func() *canvas.Image {
		img := &canvas.Image{File: "", FillMode: canvas.ImageFillStretch}
		img.SetMinSize(fyne.Size{Width: 256, Height: 256})
		return img
	}()
	g.iconImage = func() *canvas.Image {
		img := &canvas.Image{File: "", FillMode: canvas.ImageFillOriginal}
		img.SetMinSize(fyne.Size{Width: 64, Height: 64})
		return img
	}()
	g.mainLabel = &widget.Label{Text: "Welcome to MetroGnome!", TextStyle: fyne.TextStyle{Bold: true, Italic: false, Monospace: true, Symbol: false, TabWidth: 0, Underline: false}, Alignment: 1, Wrapping: 0}
	g.muteButton = widget.NewButtonWithIcon("Mute", theme.VolumeMuteIcon(), g.muteAction)
	g.pauseButton = widget.NewButtonWithIcon("Pause", theme.MediaPauseIcon(), g.pauseTap)
	g.pb = &widget.ProgressBar{Value: 0.000000}
	g.restartButton = widget.NewButtonWithIcon("Restart", theme.MediaReplayIcon(), g.restartTap)
	g.startButton = widget.NewButtonWithIcon("Start", theme.MediaPlayIcon(), g.startTap)
	g.statLabel = &widget.Label{Text: "", TextStyle: fyne.TextStyle{Bold: true, Italic: true, Monospace: true, Symbol: false, TabWidth: 0, Underline: false}, Alignment: 1, Wrapping: 0}
	g.stopButton = widget.NewButtonWithIcon("Stop", theme.MediaStopIcon(), g.stopTap)
	g.labelBox = container.NewVBox(
		g.mainLabel,
		g.statLabel)
	g.wideBox = container.NewHBox(
		container.NewVBox(
			g.startButton,
			g.stopButton,
			g.pauseButton,
			g.restartButton,
			widget.NewButtonWithIcon("Faster", theme.MoveUpIcon(), g.upTap),
			widget.NewButtonWithIcon("Slower", theme.MoveDownIcon(), g.downTap),
			g.muteButton),
		container.NewVBox(
			g.gnomeSelect,
			g.gnomes))

	return container.NewCenter(
		container.NewVBox(
			container.NewHBox(
				g.iconImage,
				g.labelBox),
			g.pb,
			g.wideBox))
}

func (g *gui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("main.gui.go")
	g.win = w
	w.SetContent(g.makeUI())
	return w
}